2021-01-25 16:15:17,299 INFO    MainThread:12008 [wandb_setup.py:_flush():70] setting env: {}
2021-01-25 16:15:17,299 INFO    MainThread:12008 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-25 16:15:17,299 INFO    MainThread:12008 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-25 16:15:17,300 INFO    MainThread:12008 [wandb_init.py:_log_setup():318] Logging user logs to D:\4A\Projet\r3g\r3g-flask\wandb\run-20210125_161517-1vvk2wlv\logs\debug.log
2021-01-25 16:15:17,300 INFO    MainThread:12008 [wandb_init.py:_log_setup():319] Logging internal logs to D:\4A\Projet\r3g\r3g-flask\wandb\run-20210125_161517-1vvk2wlv\logs\debug-internal.log
2021-01-25 16:15:22,470 INFO    MainThread:12008 [wandb_run.py:_console_start():1308] atexit reg
2021-01-25 16:15:22,471 INFO    MainThread:12008 [wandb_run.py:_redirect():1175] redirect: SettingsConsole.WRAP
2021-01-25 16:15:22,472 INFO    MainThread:12008 [wandb_run.py:_redirect():1206] Wrapping output streams.
2021-01-25 16:15:22,472 INFO    MainThread:12008 [wandb_run.py:_redirect():1222] Redirects installed.
2021-01-25 16:15:22,472 INFO    MainThread:12008 [wandb_run.py:_atexit_cleanup():1278] got exitcode: 0
2021-01-25 16:15:22,472 INFO    MainThread:12008 [wandb_run.py:_restore():1250] restore
2021-01-25 16:15:22,989 INFO    MainThread:12008 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "b9ea55412f9843a7802074221b59b71d"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 770
      total_bytes: 770
    }
  }
}

2021-01-25 16:15:25,000 INFO    MainThread:12008 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "2ba0736497f1442a89e274c40a1329c1"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 5608
      total_bytes: 5608
    }
  }
}

2021-01-25 16:15:26,173 INFO    MainThread:12008 [wandb_run.py:_show_files():1614] logging synced files
2021-01-25 16:15:26,181 INFO    MainThread:12008 [internal.py:handle_exit():139] Internal process exited
