2020/02/13 11:16:50 (1581589010750): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:16:50 (1581589010766): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:16:51 (1581589011127): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:16:51 (1581589011128): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:18:40 (1581589120454): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:18:40 (1581589120470): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:18:41 (1581589121172): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:18:41 (1581589121174): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:27:24 (1581589644467): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:27:24 (1581589644468): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:27:29 (1581589649085): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:27:29 (1581589649086): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:27:31 (1581589651619): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:27:31 (1581589651621): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:36:15 (1581590175631): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:36:15 (1581590175648): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:36:16 (1581590176376): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:36:16 (1581590176377): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:36:58 (1581590218118): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:36:58 (1581590218120): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:00 (1581590400721): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:00 (1581590400723): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:10 (1581590410811): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:10 (1581590410815): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:21 (1581590421026): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:21 (1581590421028): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:25 (1581590425645): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:25 (1581590425647): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:36 (1581590436037): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:40:36 (1581590436038): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:41:25 (1581590485921): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:41:25 (1581590485923): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:41:36 (1581590496157): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:41:36 (1581590496159): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:41:50 (1581590510602): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:41:50 (1581590510604): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:42:45 (1581590565960): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:42:45 (1581590565961): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:42:56 (1581590576011): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:42:56 (1581590576013): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:43:05 (1581590585723): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:43:05 (1581590585725): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:08 (1581590648364): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:08 (1581590648366): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:16 (1581590656045): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:16 (1581590656047): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:20 (1581590660862): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:20 (1581590660863): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:40 (1581590680714): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:40 (1581590680716): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:46 (1581590686021): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:44:46 (1581590686023): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:46:26 (1581590786096): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:46:26 (1581590786098): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:46:36 (1581590796068): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:46:36 (1581590796070): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:46:51 (1581590811310): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:46:51 (1581590811312): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:00 (1581590820847): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:00 (1581590820849): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:11 (1581590831260): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:11 (1581590831261): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:20 (1581590840918): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:20 (1581590840920): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:41 (1581590861047): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:41 (1581590861048): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:47 (1581590867232): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:47:47 (1581590867234): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:48:06 (1581590886121): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:48:06 (1581590886123): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:48:36 (1581590916349): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:48:36 (1581590916350): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:48:46 (1581590926355): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:48:46 (1581590926358): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:49:01 (1581590941942): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:49:01 (1581590941943): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:49:06 (1581590946022): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:49:06 (1581590946025): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:49:31 (1581590971073): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:49:31 (1581590971075): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 11:51:37 (1581591097031): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:51:37 (1581591097032): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:59:44 (1581591584416): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:59:44 (1581591584417): ServiceDiscoveryClientUdp : Start 
2020/02/13 11:59:48 (1581591588824): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 11:59:48 (1581591588826): ServiceDiscoveryClientUdp : Start 
2020/02/13 12:00:25 (1581591625016): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 12:00:25 (1581591625034): ServiceDiscoveryClientUdp : Start 
2020/02/13 12:00:25 (1581591625782): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 12:00:25 (1581591625784): ServiceDiscoveryClientUdp : Start 
2020/02/13 12:05:10 (1581591910125): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 12:05:10 (1581591910146): ServiceDiscoveryClientUdp : Start 
2020/02/13 12:21:09 (1581592869945): IntuiScriptDatabase : SaveClazz : insert/update error  
2020/02/13 12:26:02 (1581593162109): SynchronisationClient : Transform error refit ex : System.Threading.Tasks.TaskCanceledException: A task was canceled. 
2020/02/13 14:06:12 (1581599172756): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 14:06:12 (1581599172773): ServiceDiscoveryClientUdp : Start 
2020/02/13 14:06:13 (1581599173465): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 14:06:13 (1581599173466): ServiceDiscoveryClientUdp : Start 
2020/02/13 14:07:41 (1581599261260): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 14:07:41 (1581599261262): ServiceDiscoveryClientUdp : Start 
2020/02/13 14:11:36 (1581599496271): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 14:11:36 (1581599496272): ServiceDiscoveryClientUdp : Start 
2020/02/13 14:12:14 (1581599534396): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 14:12:14 (1581599534399): ServiceDiscoveryClientUdp : Start 
2020/02/13 16:36:52 (1581608212576): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 16:36:52 (1581608212594): ServiceDiscoveryClientUdp : Start 
2020/02/13 16:36:53 (1581608213372): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 16:36:53 (1581608213373): ServiceDiscoveryClientUdp : Start 
2020/02/13 16:38:12 (1581608292543): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 16:38:12 (1581608292545): ServiceDiscoveryClientUdp : Start 
2020/02/13 16:38:29 (1581608309292): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/13 16:38:29 (1581608309294): ServiceDiscoveryClientUdp : Start 
2020/02/13 16:59:07 (1581609547351): SynchronisationClient : SynchronizeLog erreur sync log /storage/emulated/0/Android/data/com.learnandgo.kaligo/files/480783e8-05fa-42a3-8a66-4c6b408e7cda/Logs/essai9_13-f√©vrier-2020_16.56.15/strokes.inkml : System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SynchronizeLog () [0x0024b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:14 (1581609674655): SynchronisationClient : SynchronizeLog erreur sync log /storage/emulated/0/Android/data/com.learnandgo.kaligo/files/480783e8-05fa-42a3-8a66-4c6b408e7cda/Logs/essai9_13-f√©vrier-2020_16.56.15/interaction.xml : System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SynchronizeLog () [0x0024b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:15 (1581609675943): SynchronisationClient : Transform error refit ex : System.Threading.Tasks.TaskCanceledException: A task was canceled. 
2020/02/13 17:01:15 (1581609675988): SynchronisationClient : Queue task:610044538 execution : System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:21 (1581609681052): SynchronisationClient : Transform error refit ex : System.Threading.Tasks.TaskCanceledException: A task was canceled. 
2020/02/13 17:01:21 (1581609681064): SynchronisationClient : Queue task:35644191 execution : System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:21 (1581609681995): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:22 (1581609682242): SynchronisationClient : Queue task:954154036 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:24 (1581609684992): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:25 (1581609685008): SynchronisationClient : Queue task:888433040 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:27 (1581609687991): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:28 (1581609688004): SynchronisationClient : Queue task:314032821 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:30 (1581609690993): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:31 (1581609691004): SynchronisationClient : Queue task:34170780 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:33 (1581609693991): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:34 (1581609694008): SynchronisationClient : Queue task:952680625 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:36 (1581609696992): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:37 (1581609697008): SynchronisationClient : Queue task:378018390 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:39 (1581609699996): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:40 (1581609700011): SynchronisationClient : Queue task:768978480 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:42 (1581609702992): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:43 (1581609703009): SynchronisationClient : Queue task:194316245 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:45 (1581609705992): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:46 (1581609706004): SynchronisationClient : Queue task:683588535 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:48 (1581609708992): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:49 (1581609709009): SynchronisationClient : Queue task:125703532 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:51 (1581609711991): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:52 (1581609712007): SynchronisationClient : Queue task:1026649601 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:54 (1581609714992): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:55 (1581609715008): SynchronisationClient : Queue task:85121836 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:01:57 (1581609717991): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:01:58 (1581609718007): SynchronisationClient : Queue task:243040373 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:00 (1581609720992): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:02:01 (1581609721004): SynchronisationClient : Queue task:608164138 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:03 (1581609723991): SynchronisationClient : Transform error refit ex : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0  
2020/02/13 17:02:04 (1581609724001): SynchronisationClient : Queue task:805193498 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:04 (1581609724008): SynchronisationClient : Queue task:146450776 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.c (IntuiScript.Model.Exercise.MileStone ahc) [0x0009f] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:07 (1581609727001): SynchronisationClient : Queue task:949656122 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:07 (1581609727001): SynchronisationClient : Queue task:71287344 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:07 (1581609727001): SynchronisationClient : Queue task:142085013 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:10 (1581609730001): SynchronisationClient : Queue task:648954109 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:10 (1581609730001): SynchronisationClient : Queue task:664018423 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:10 (1581609730001): SynchronisationClient : Queue task:972537335 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:13 (1581609733002): SynchronisationClient : Queue task:581278242 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.h (IntuiScript.Model.Exercise.Ex11.Ex11ExerciseContent ahh) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x002ff] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:13 (1581609733002): SynchronisationClient : Queue task:693498732 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:13 (1581609733002): SynchronisationClient : Queue task:758991765 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:16 (1581609736003): SynchronisationClient : Queue task:585012987 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:16 (1581609736003): SynchronisationClient : Queue task:302262431 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.h (IntuiScript.Model.Exercise.Ex11.Ex11ExerciseContent ahh) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x002ff] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:16 (1581609736005): SynchronisationClient : Queue task:681250533 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:19 (1581609739016): SynchronisationClient : Queue task:906643061 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:19 (1581609739016): SynchronisationClient : Queue task:363102791 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:19 (1581609739021): SynchronisationClient : Queue task:955623041 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.h (IntuiScript.Model.Exercise.Ex11.Ex11ExerciseContent ahh) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x002ff] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:22 (1581609742010): SynchronisationClient : Queue task:417483665 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/13 17:02:22 (1581609742010): SynchronisationClient : Queue task:225439173 execution : System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x00110] in <f68e83454f864b9ba23426db296cae72>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.ConnectAsync (System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x001ac] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00134] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <f68e83454f864b9ba23426db296cae72>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <f68e83454f864b9ba23426db296cae72>:0 
  at Refit.RequestBuilderImplementation+<>c__DisplayClass14_0`2[T,TBody].<BuildCancellableTaskFuncForMethod>b__0 (System.Net.Http.HttpClient client, System.Threading.CancellationToken ct, System.Object[] paramList) [0x00188] in <dbbbbd6465bb4f5d88b000e5d8096615>:0 
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <9ce90c81f389405fa2d38b0e75e8871b>:0 
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <99f8205c51c44bb480747b577b8001ff>:0 
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <ce814a9f945b4adf9ecc761b277d2ee9>:0 
  at IntuiScript.Service.Network.SynchronisationClient.b (IntuiScript.Model.Exercise.IExerciseContent ahb) [0x000a8] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.i (IntuiScript.Model.Exercise.Ex12.Ex12ExerciseContent ahi) [0x0015b] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient.SendExerciseContent (IntuiScript.Model.Exercise.IExerciseContent exercise) [0x00364] in <00e32050f0c14b5d93868f3f42f84132>:0 
  at IntuiScript.Service.Network.SynchronisationClient+c.a () [0x0007b] in <00e32050f0c14b5d93868f3f42f84132>:0  
2020/02/20 16:32:39 (1582212759921): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/20 16:32:39 (1582212759939): ServiceDiscoveryClientUdp : Start 
2020/02/20 16:32:40 (1582212760650): ServiceDiscoveryClientUdp : StartDiscovery 
2020/02/20 16:32:40 (1582212760651): ServiceDiscoveryClientUdp : Start 
